#!/bin/sh

type=$1
echo "postrm="$type

LOCAL_DIR=/usr/local
ROOT_DIR=/
AIGO_USER=aigo

if [ x"$type" = x"remove" ] ; then
	rm -f $LOCAL_DIR/bin/aigo_config
	rm -f $LOCAL_DIR/share/applications/aigo_config.desktop
	rm -f $LOCAL_DIR/share/pixmaps/aigo.png
	rm -f $LOCAL_DIR/bin/aigo_look.sh
	rm -f $ROOT_DIR/etc/aigo_version
	
	mkdir /opt
	chown root.root /opt
	chmod 0755 /opt
fi

exit 0
