#!/bin/sh

type=$1
echo "postinst="$type

AIGO_TOOLS_DIR=/opt/aigo
LOCAL_DIR=/usr/local
ROOT_DIR=/
AIGO_USER=aigo
AIGO_HOME=/home/$AIGO_USER
LXQTPANEL_CONF_DIR=$AIGO_HOME/.config/lxqt
LXQTPANEL_CONF=panel.conf

chfile() {
        FNAME=$1
        FDIR=$2
        OWN=$3
        MOD=$4

        rm -rf $FDIR/$FNAME
        mkdir -p $FDIR
        cp -f $AIGO_TOOLS_DIR/$FNAME $FDIR
        chown $OWN $FDIR/$FNAME
        chmod $MOD $FDIR/$FNAME
}

chfile aigo_config $LOCAL_DIR/bin root.root 755
chfile aigo_config.desktop $LOCAL_DIR/share/applications root.root 644
chfile aigo.png $LOCAL_DIR/share/pixmaps root.root 644
chfile aigo_look.sh $LOCAL_DIR/bin root.root 755
chfile aigo_version $ROOT_DIR/etc root.root 644

chown root.root /etc/aigo*
chmod 644 /etc/aigo*

chown root.root /opt/aigo
chmod 755 /opt/aigo
chown root.root /opt/aigo/*
chmod 644 /opt/aigo/*
chmod 755 /opt/aigo/aigo_init-resize.sh

chown root.root /etc/sudoers.d/aigo*
chmod 440 /etc/sudoers.d/aigo*

chown root.root /usr/local/bin/aigo*
chmod 755 /usr/local/bin/aigo*

chown root.root /usr/local/share/applications/aigo*
chmod 644 /usr/local/share/applications/aigo*

chown root.root /usr/local/share/pixmaps/aigo*
chmod 644 /usr/local/share/pixmaps/aigo*

chown www-data.www-data /var/www/html
chmod 755 /var/www/html
chown www-data.www-data /var/www/html/*.php
chmod 644 /var/www/html/*.php

exit 0
